### ISSUE TITLE
Acceptance tests feature files have possible command typo

### ISSUE THREAD

**Issue by rkeeves** [epam-deik-cooperation/epam-deik-java-dev#6]
Impacting `final > ticket-service-acceptance-tests`

I rant into what seems to be a typo in the acceptance tests.
Maybe these are intentional, I just wanted to bring them to light.

## Context

The command for creating an account is `sign up`,
but some acceptance test scenarios use `create account` instead.
In the README I wasn't able to find an explanation for this.

> This issue only comes up if you run `grade4` or `grade5` tests.

## Process

0. Implement everything according to README
1. `mvn clean verify -P requirements-grade4`
2. verification ends

## Expected Result

The maven verify should pass.

## Current Result

The maven verify fails, because there's no `create account` command.

It seems to me that the following files and scenarios are impacted:

#### movies.feature

```
@grade4-requirement
Scenario: an authenticated, non-privileged user can list movies
...
And the user types the "create account sanyi asdQWE123" command
...
```

#### rooms.feature

```
@grade4-requirement
Scenario: an authenticated, non-privileged user can list rooms
...
And the user types the "create account sanyi asdQWE123" command
...
```

## Possible Fixes

* Add `create account` key to the keyset of ShellCommand, and mention it in README 
* Fix the acceptance tests, and replace all occurrences of `create account` with `sign up`

**Comment by ferencbarta** [comment]
Thank you @rkeeves for reporting this. The fix is included in #16
